name: Hello
on:
 push:
   branches: [main]
   paths:
     - '**.html'

jobs:
  greet:
     runs-on: ubuntu-latest
     
     steps:
      - name: say hello
        run: echo "hello baby"
       
      - name: say username
        run: echo "$USER"

  details:
     runs-on: ubuntu-latest

     steps:
       - name: check verion of docker and python
         run: docker --version && python --version

 
